name: system_info_toolkit
description: "A new Flutter package"
version: 0.0.1
homepage: https://github.com/Sude2012/system_info_toolkit
repository: https://github.com/Sude2012/system_info_toolkit.git

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.sude.system_info_toolkit
        pluginClass: SystemInfoToolkitPlugin
      ios:
        pluginClass: SystemInfoToolkitPlugin
